// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2VYX9i9UMvrtsM3t6wzBqTj18vMr29oc',
    appId: '1:235403597235:web:bf817e7fefee9bbc5ca7c6',
    messagingSenderId: '235403597235',
    projectId: 'senior-capston',
    authDomain: 'senior-capston.firebaseapp.com',
    storageBucket: 'senior-capston.appspot.com',
    measurementId: 'G-DMQQHPKHHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCviUQC59tH-aHOvW_DeO6OcyzOHEKcCqg',
    appId: '1:235403597235:android:3fb5f664f169fb105ca7c6',
    messagingSenderId: '235403597235',
    projectId: 'senior-capston',
    storageBucket: 'senior-capston.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjzFWtxA1AeXBuDHMRuvy9ujY21cwzr0',
    appId: '1:235403597235:ios:cea8897689bac2b15ca7c6',
    messagingSenderId: '235403597235',
    projectId: 'senior-capston',
    storageBucket: 'senior-capston.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjzFWtxA1AeXBuDHMRuvy9ujY21cwzr0',
    appId: '1:235403597235:ios:88618a7499a931ad5ca7c6',
    messagingSenderId: '235403597235',
    projectId: 'senior-capston',
    storageBucket: 'senior-capston.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
